export const searchData = [
  {
    label: "Admin",
    sublabels: {
      "Association of Pacific Rim Universities": "",
      "Bukit Timah Campus Management Office": "",
      "Centre for Development of Teaching & Learning": "",
      "Centre for Future-ready Graduates": "",
      "Centre for Instructional Technology": ["Computer Centre", "House 11", "Central Library Annexe"],
      "Computer Centre": "",
      "Development Office": "",
      "Engineering Design and Innovation Centre": "",
      "NUS Museum": "",
      "NUS Industry Liaison Office": "",
      "International Relations Office": "",
      "Investment Office": "",
      "NUS": "Suzhou) Research Institute Liaison Offic",
      "NUS Centre For the Arts": "",
      "NUS Enterprise": "",
      "NUS Entrepreneurship Centre": "",
      "NUS Overseas Colleges": "",
      "NUS Press": "",
      "Office of Admissions": "",
      "Office of Alumni Relations": "",
      "Office of Campus Amenities": "",
      "Office of Campus Security": ["House 17", "House 18"],
      "Office of Corporate Relations": "",
      "Office of Estate Development": "",
      "Office of Financial Aid": "",
      "Office of Financial Services": "",
      "Office of Housing Services": "",
      "Office of Human Resources": "",
      "Office of Internal Audit": "",
      "Office of Legal Affairs": "",
      "Office of Life Sciences": "",
      "Office of Resource Planning": "",
      "Office of Risk Management": "",
      "Office of Safety, Health & Environment": "",
      "Office of Student Affairs": "",
      "Office of the Deputy President": ["Administration", "Research & Technology"],
      "Office of the President": "",
      "Office of the Provost": "",
      "Organisational Excellence Office": "",
      "University Health Centre": "",
      "WHO Collaborating Centre for Occupational Health": ""
    }
  },
  {
    label: "Schools",
    sublabels: {
      "Arts & Social Sciences": "",
      "Business": "",
      "Computing": "",
      "Dentistry": "",
      "Design & Environment": "",
      "Engineering": "",
      "Integrative Sciences & Engineering": "",
      "Medicine": "",
      "Music": "",
      "Public Health": "",
      "Science": "",
      "University Scholars Programme": "",
      "Yale-NUS College": ""
    }
  },
  {
    label: "Departments / Facilities",
    sublabels: {
      "Arts & Social Sciences": {
        "AS1": "",
        "AS2": "",
        "AS3": "",
        "AS4": "",
        "AS5": "",
        "AS6": "",
        "AS7": "",
        "Centre for Language Studies": "",
        "Communications & New Media Programme": "",
        "Faculty of Arts Social Sciences": "Dean's Office",
        "Department of Chinese Studies": "",
        "Department of Economics": "",
        "Department of English Language & Literature": "",
        "Department of Geography": "",
        "Department of History": "",
        "Department of Japanese Studies": "",
        "Department of Malay Studies": "",
        "Department of Philosophy": "",
        "Department of Political Science": "",
        "Department of Psychology": "",
        "Department of Social Work": "",
        "Department of Sociology": "",
        "Division of Research & Graduate Studies": "Faculty of Arts & Social Sciences",
        "Office of Programmes": "Faculty of Arts & Social Sciences",
        "Singapore Centre for Applied and Policy Economics": "SCAPE",
        "South Asian Studies Programme": "",
        "Southeast Asian Studies Programme": ""
    },
      "Business": {
        "BIZ1": "",
        "BIZ2": "",
        "Centre for e-Business": "",
        "Department of Accounting": "",
        "Department of Decision Sciences": "",
        "Department of Finance": "",
        "Department of Management & Organisation": "",
        "Department of Marketing": "",
        "Division of Research & Graduate Studies": "NUS Business School",
        "Saw Centre for Financial Studies": ""
      },
      "Computing": {
        "COM1": "",
        "COM2": "",
        "Adaptive Computing Research Lab": "",
        "Computational Biology Research Lab": "",
        "Computational Linguistics Research Lab": "",
        "Computer Vision Research Lab": "",
        "Database Research Lab 1": "",
        "School of Computing": "Dean's Office",
        "Department of Computer Science": "",
        "Department of Information Systems": "",
        "Electronic Commerce & Database Research Lab": "",
        "Embedded Systems Research Lab 1": "",
        "Embedded Systems Research Lab 2": "",
        "G^3 Lab": "",
        "Industry Research Lab": "",
        "Lab for Media Search": "",
        "Medical Computing Research Lab": "",
        "Multimedia Analysis and Synthesis Lab": "",
        "Multimedia Systems Lab": "",
        "Programming Languages & Systems Research Lab 1": "",
        "Sensors Lab": "",
        "Incubation Centre": "School of Computing"
      },
      "Dentistry": {
        "Faculty of Dentistry": "Dean's Office",
        "Department of Oral & Maxillofacial Surgery": "",
        "Department of Preventive Dentistry": "",
        "Department of Restorative Dentistry": "",
        "Division of Graduate Dental Studies": ""
      },
      "Design & Environment": "",
      "Engineering": "",
      "Integrative Sciences & Engineering": "",
      "Medicine": "",
      "Music": "",
      "Public Health": "",
      "Science": "",
      "University Scholars Programme": "",
      "Yale-NUS College": ""
    }
  }
];